// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_printone

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func PrintoneProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type PrintoneModel struct {
}
