// Copyright (c) Plain Technologies Aps

// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_webhook

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func WebhookResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether the webhook is active",
				MarkdownDescription: "Whether the webhook is active",
			},
			"events": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "List of events to subscribe to",
				MarkdownDescription: "List of events to subscribe to",
			},
			"headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "A map of headers to add to each webhook call",
				MarkdownDescription: "A map of headers to add to each webhook call",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the webhook",
				MarkdownDescription: "The id of the webhook",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The custom name of the webhook",
				MarkdownDescription: "The custom name of the webhook",
			},
			"secret_headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "A map of headers with secret values, which will not be visible after saving",
				MarkdownDescription: "A map of headers with secret values, which will not be visible after saving",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "The callback of the webhook",
				MarkdownDescription: "The callback of the webhook",
			},
		},
	}
}

type WebhookModel struct {
	Active        types.Bool   `tfsdk:"active"`
	Events        types.List   `tfsdk:"events"`
	Headers       types.Map    `tfsdk:"headers"`
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	SecretHeaders types.Map    `tfsdk:"secret_headers"`
	Url           types.String `tfsdk:"url"`
}
