// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_webhooksecret

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func WebhooksecretDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"secret": schema.StringAttribute{
				Computed:            true,
				Description:         "Secret used for signing webhook payloads",
				MarkdownDescription: "Secret used for signing webhook payloads",
			},
		},
	}
}

type WebhooksecretModel struct {
	Secret types.String `tfsdk:"secret"`
}
