// Copyright (c) Plain Technologies Aps

// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_webhook

import (
	"context"

		"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
		"github.com/hashicorp/terraform-plugin-framework/types"
		"github.com/hashicorp/terraform-plugin-framework/attr"
)

func WebhookDataSourceSchema(ctx context.Context) schema.Schema {
   return schema.Schema{
	   Attributes: map[string]schema.Attribute{
		   "filters": schema.ListAttribute{
			   ElementType: types.ObjectType{AttrTypes: map[string]attr.Type{
				   "key":    types.StringType,
				   "event":  types.StringType,
				   "type":   types.StringType,
				   "value":  types.StringType,
				   "values": types.ListType{ElemType: types.StringType},
			   }},
			   Computed:            true,
			   Description:         "List of filters for the webhook",
			   MarkdownDescription: "List of filters for the webhook",
		   },
			"active": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the webhook is active",
				MarkdownDescription: "Whether the webhook is active",
			},
			"events": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "List of events to subscribe to",
				MarkdownDescription: "List of events to subscribe to",
			},
			"headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "A map of headers to add to each webhook call",
				MarkdownDescription: "A map of headers to add to each webhook call",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The id of the webhook",
				MarkdownDescription: "The id of the webhook",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The custom name of the webhook",
				MarkdownDescription: "The custom name of the webhook",
			},
			"secret_headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "A map of headers with secret values, the values will always be '** SecretValue **'",
				MarkdownDescription: "A map of headers with secret values, the values will always be '** SecretValue **'",
			},
			"success_rate": schema.NumberAttribute{
				Computed:            true,
				Description:         "Percentage of calls to the webhook that have been successful",
				MarkdownDescription: "Percentage of calls to the webhook that have been successful",
			},
			"url": schema.StringAttribute{
				Computed:            true,
				Description:         "The callback of the webhook",
				MarkdownDescription: "The callback of the webhook",
			},
		},
	}
}

type WebhookModel struct {
	Filters       types.List   `tfsdk:"filters"`
	Active        types.Bool   `tfsdk:"active"`
	Events        types.List   `tfsdk:"events"`
	Headers       types.Map    `tfsdk:"headers"`
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	SecretHeaders types.Map    `tfsdk:"secret_headers"`
	SuccessRate   types.Number `tfsdk:"success_rate"`
	Url           types.String `tfsdk:"url"`
}
